const GLOBAL_ONLY = [
  'html','head','title','body',
  'div','span','p','main','section','article','aside','header','footer','nav',
  'h1','h2','h3','h4','h5','h6',
  'em','strong','small','sub','sup','mark','code','pre','samp','kbd','dfn',
  'b','i','u','s',
  'figure','figcaption',
  'blockquote','q','cite',
  'details','summary','dialog',
  'noscript','template','slot',
  'table','thead','tbody','tfoot','tr',
  'ul','dl','dt','dd','menu',
  'caption',
  'picture',
  'legend',
];

export const GLOBAL_ATTRIBUTE_NAMES = [
  'id',
  'className',
  'style',
  'title',
  'lang',
  'dir',
  'hidden',
  'tabIndex',
  'role',
  'draggable',
  'contentEditable',
  'spellcheck',
  'translate',
  'onclick',
  'onchange',
  'oninput',
  'onsubmit',
];

export const TAG_ATTRIBUTE_NAMES = {
  a: ['href','target','rel','download','hreflang','referrerPolicy'],
  img: ['src','alt','width','height','loading','decoding','srcset','sizes','crossOrigin','referrerPolicy','onload','onerror'],
  input: ['type','name','value','placeholder','checked','disabled','required','minLength','maxLength','min','max','step','pattern','autocomplete','accept','multiple'],
  button: ['type','disabled','name','value','autofocus'],
  form: ['action','method','enctype','autocomplete','noValidate','target'],
  script: ['src','type','async','defer','crossOrigin','integrity','referrerPolicy','noModule','onload','onerror'],
  link: ['href','rel','as','type','media','crossOrigin','integrity','referrerPolicy','sizes','onload','onerror'],
  meta: ['charset','name','content','property','httpEquiv'],
  textarea: ['name','placeholder','disabled','readOnly','required','rows','cols','minLength','maxLength','wrap'],
  label: ['htmlFor'],
  source: ['src','srcset','sizes','type','media'],
  track: ['src','kind','srclang','label','default','onload','onerror'],
  iframe: ['src','name','width','height','loading','allow','allowFullscreen','referrerPolicy','onload','onerror'],
  video: ['src','controls','autoplay','loop','muted','playsInline','preload','poster','width','height'],
  audio: ['src','controls','autoplay','loop','muted','preload'],
  select: ['name','multiple','disabled','required','size'],
  option: ['value','selected','disabled','label'],
  ol: ['start','reversed','type'],
  th: ['scope','colSpan','rowSpan','abbr'],
  td: ['colSpan','rowSpan'],
  time: ['dateTime'],
  area: ['alt','coords','download','href','hreflang','shape','target','rel','referrerPolicy'],
  map: ['name'],
  canvas: ['width','height'],
  fieldset: ['disabled','name'],
  output: ['for','name'],
  optgroup: ['disabled','label'],
  progress: ['value','max'],
  meter: ['value','min','max','low','high','optimum'],
  data: ['value'],
  base: ['href','target'],
  style: ['media'],
  embed: ['src','type','width','height'],
  object: ['data','type','name','width','height'],
  param: ['name','value'],
  colgroup: ['span'],
  col: ['span'],
  li: ['value'],
  ...Object.fromEntries(GLOBAL_ONLY.map((tag) => [tag, []])),
  br: [],
  hr: [],
  wbr: [],
  datalist: [],
  ruby: [],
  rp: [],
  rt: [],
};

// TypeScript attribute names to HTML attribute names
// for some reason, the TypeScript attribute names are not the same as the actual HTML attribute names
// e.g. "className" is "class" in HTML
// and "htmlFor" is "for" in HTML
export const NAME_MAP = {
  className: 'class',
  htmlFor: 'for',
  tabIndex: 'tabindex',
  contentEditable: 'contenteditable',
  crossOrigin: 'crossorigin',
  referrerPolicy: 'referrerpolicy',
  noValidate: 'novalidate',
  noModule: 'nomodule',
  readOnly: 'readonly',
  minLength: 'minlength',
  maxLength: 'maxlength',
  httpEquiv: 'httpEquiv',
  playsInline: 'playsinline',
  allowFullscreen: 'allowfullscreen',
  colSpan: 'colspan',
  rowSpan: 'rowspan',
  dateTime: 'datetime',
};
